export const applicationCategories = [
  '技术与开发',
  '视频与内容',
  '学术与学习',
  '办公与管理',
  '商业与增长',
  '设计与产品',
] as const;

export type ApplicationCategory = (typeof applicationCategories)[number];

export type ApplicationPlan = {
  slug: string;
  name: string;
  category: ApplicationCategory;
  summary: string;
  steps: [string, string, string];
  stack: string;
  promptQuery: string;
  guideHref?: string;
};

export const applicationPlans: ApplicationPlan[] = [
  {
    slug: 'write-code',
    name: '写代码',
    category: '技术与开发',
    summary: '从需求拆解到实现、测试和代码审查，减少返工。',
    steps: ['提供需求、接口和约束', '先设计方案再分段实现', '运行测试并人工审查变更'],
    stack: '编程模型 + IDE Agent',
    promptQuery: '代码',
  },
  {
    slug: 'build-website',
    name: '做网站',
    category: '技术与开发',
    summary: '完成信息架构、页面实现、响应式适配和上线检查。',
    steps: ['明确用户、页面和视觉参考', '先做核心页面再补细节', '检查移动端、链接和部署'],
    stack: '编程模型 + 多模态设计模型',
    promptQuery: '编程开发',
  },
  {
    slug: 'debug-code',
    name: '调试排错',
    category: '技术与开发',
    summary: '用日志、复现步骤和最小实验定位 Bug 根因。',
    steps: ['整理现象、日志和最近变更', '建立假设并设计最小实验', '验证修复、回归和回滚方案'],
    stack: '强推理模型 + 代码执行环境',
    promptQuery: 'Bug 根因定位',
  },
  {
    slug: 'design-api',
    name: '设计 API',
    category: '技术与开发',
    summary: '设计清晰、稳定、可演进的接口契约和错误模型。',
    steps: ['提供业务动作和数据边界', '设计资源、状态码和版本策略', '生成契约测试与示例'],
    stack: '编程模型 + API 测试工具',
    promptQuery: 'API 接口设计',
  },
  {
    slug: 'automate-work',
    name: '自动化重复工作',
    category: '技术与开发',
    summary: '把重复流程拆成触发、处理、检查和异常升级。',
    steps: ['记录现有流程和例外情况', '先删除无效步骤再自动化', '增加日志、权限和人工兜底'],
    stack: 'Agent 模型 + 自动化平台',
    promptQuery: '流程优化',
  },
  {
    slug: 'review-sql',
    name: '写 SQL 与查数据',
    category: '技术与开发',
    summary: '从指标口径到查询、性能检查和结果解释。',
    steps: ['提供表结构和指标定义', '生成只读查询并解释逻辑', '检查性能、边界值和样本'],
    stack: '强推理模型 + 只读数据环境',
    promptQuery: 'SQL',
  },
  {
    slug: 'edit-video',
    name: '剪视频',
    category: '视频与内容',
    summary: '把素材整理成节奏清楚、重点明确的成片方案。',
    steps: ['提供素材清单、受众和平台', '生成粗剪结构与时间轴', '补字幕、包装并人工看完整片'],
    stack: 'ChatGPT + 剪映',
    promptQuery: '内容生产',
    guideHref: '/roles/video-editing',
  },
  {
    slug: 'short-video-script',
    name: '写短视频脚本',
    category: '视频与内容',
    summary: '设计开场钩子、信息节奏、镜头和行动引导。',
    steps: ['明确平台、时长和目标受众', '生成口播、镜头与字幕表', '核查事实并试读计时'],
    stack: '创作模型 + 搜索工具',
    promptQuery: '内容生产',
  },
  {
    slug: 'write-article',
    name: '写文章',
    category: '视频与内容',
    summary: '从资料、观点和提纲生成有证据的完整文章。',
    steps: ['提供读者、观点和可信资料', '先确认提纲再逐段撰写', '核对事实、引用和语气'],
    stack: '长文本模型 + 事实核查工具',
    promptQuery: '商业写作',
  },
  {
    slug: 'make-slides',
    name: '做 PPT',
    category: '视频与内容',
    summary: '把复杂材料整理成结构清晰、可以讲述的演示稿。',
    steps: ['明确观众和需要的决定', '先做故事线与逐页标题', '补证据、视觉建议并彩排'],
    stack: '长文本模型 + 演示文稿工具',
    promptQuery: '演讲',
  },
  {
    slug: 'organize-interview',
    name: '整理访谈与播客',
    category: '视频与内容',
    summary: '从录音转写中提取主题、金句、争议和内容切片。',
    steps: ['转写并标记说话人和时间', '归纳主题与证据原句', '生成摘要、标题和切片清单'],
    stack: '语音转写 + 长文本模型',
    promptQuery: '用户访谈分析',
  },
  {
    slug: 'translate-localize',
    name: '翻译与本地化',
    category: '视频与内容',
    summary: '不仅翻译文字，还统一术语、语气和当地表达。',
    steps: ['提供受众、地区和术语表', '按语境翻译并标出歧义', '母语复核文化与合规风险'],
    stack: '多语言模型 + 术语库',
    promptQuery: '本地化',
  },
  {
    slug: 'revise-paper',
    name: '修改学术论文',
    category: '学术与学习',
    summary: '检查论证、结构、方法、证据和学术表达。',
    steps: ['提供论文、目标期刊和规范', '先审论证再修改语言', '逐项核查引用且保留修订说明'],
    stack: '长上下文模型 + 文献管理工具',
    promptQuery: '论文同行评审',
  },
  {
    slug: 'literature-review',
    name: '做文献综述',
    category: '学术与学习',
    summary: '系统检索、筛选、比较和综合已有研究。',
    steps: ['定义研究问题和纳入标准', '建立检索式与证据表', '综合共识、分歧和研究空白'],
    stack: '深度研究工具 + 长文本模型',
    promptQuery: '研究资料综述',
  },
  {
    slug: 'research-design',
    name: '设计研究方案',
    category: '学术与学习',
    summary: '把研究问题变成可执行、可检验的方法方案。',
    steps: ['明确问题、变量和理论依据', '比较方法、样本和分析策略', '检查偏差、伦理和可重复性'],
    stack: '强推理模型 + 统计工具',
    promptQuery: '学术研究设计',
  },
  {
    slug: 'learn-topic',
    name: '学习新知识',
    category: '学术与学习',
    summary: '按已有水平设计学习路径、练习和反馈循环。',
    steps: ['说明目标、基础和时间', '建立概念地图与分阶段课程', '通过练习和复述检验理解'],
    stack: '辅导模型 + 权威检索工具',
    promptQuery: '课程教学设计',
  },
  {
    slug: 'exam-practice',
    name: '备考与出题',
    category: '学术与学习',
    summary: '围绕考试范围生成练习、评分和薄弱点复习计划。',
    steps: ['提供考纲、题型和样题', '按难度生成题目与答案', '分析错题并动态调整计划'],
    stack: '长文本模型 + 题库资料',
    promptQuery: '学习评价量表',
  },
  {
    slug: 'design-course',
    name: '设计课程',
    category: '学术与学习',
    summary: '从学习目标反推内容、活动、作业和评价。',
    steps: ['定义学员和可观察目标', '设计课程结构与课堂活动', '建立作业、量表和改进机制'],
    stack: '推理模型 + 教学资料',
    promptQuery: '课程教学设计',
  },
  {
    slug: 'meeting-notes',
    name: '整理会议纪要',
    category: '办公与管理',
    summary: '把会议记录整理成决定、行动项、负责人和期限。',
    steps: ['提供录音、转写或原始笔记', '区分讨论、决定和未决问题', '确认负责人、截止日期和通知对象'],
    stack: '语音转写 + 长文本模型',
    promptQuery: '管理会议决策',
  },
  {
    slug: 'work-report',
    name: '写工作汇报',
    category: '办公与管理',
    summary: '用结论、证据、风险和请求组织周报或高管汇报。',
    steps: ['明确汇报对象和所需决定', '整理成果、指标和偏差', '压缩成结论优先的结构'],
    stack: '分析模型 + 演示文稿工具',
    promptQuery: '高管汇报结构',
  },
  {
    slug: 'project-plan',
    name: '制定项目计划',
    category: '办公与管理',
    summary: '拆解范围、里程碑、依赖、资源和风险。',
    steps: ['明确目标、边界和验收标准', '拆分里程碑、任务和依赖', '建立风险、沟通和变更机制'],
    stack: '强推理模型 + 项目管理工具',
    promptQuery: '项目风险登记',
  },
  {
    slug: 'write-sop',
    name: '编写 SOP',
    category: '办公与管理',
    summary: '把经验变成任何合格成员都能执行的标准流程。',
    steps: ['访谈实际执行者并收集案例', '写清角色、步骤和完成证据', '补异常处理并现场试跑'],
    stack: '长文本模型 + 流程图工具',
    promptQuery: 'SOP 流程编写',
  },
  {
    slug: 'recruit-interview',
    name: '招聘与面试',
    category: '办公与管理',
    summary: '建立岗位标准、结构化问题和一致评分规则。',
    steps: ['定义岗位成果和关键能力', '设计行为问题与追问', '独立评分并核查偏差'],
    stack: '长文本模型 + 结构化评分表',
    promptQuery: '招聘标准设计',
  },
  {
    slug: 'review-contract',
    name: '审查合同',
    category: '办公与管理',
    summary: '识别关键条款、商业风险和需要专业复核的问题。',
    steps: ['说明交易背景和我方底线', '逐条标记风险与建议修改', '交由合格律师完成最终复核'],
    stack: '长上下文模型 + 专业法务复核',
    promptQuery: '合同风险审查',
  },
  {
    slug: 'market-research',
    name: '市场与竞品调研',
    category: '商业与增长',
    summary: '用可信来源比较市场、客户、竞品和机会空间。',
    steps: ['定义市场边界和关键问题', '搜集一手来源并建立对比表', '区分事实、推断和待验证假设'],
    stack: '联网研究模型 + 表格工具',
    promptQuery: '竞品深度分析',
  },
  {
    slug: 'marketing-copy',
    name: '写营销文案',
    category: '商业与增长',
    summary: '围绕受众问题、价值证据和渠道格式生成文案。',
    steps: ['提供受众、产品和品牌语气', '生成多个角度与版本', '核查承诺并进行小流量测试'],
    stack: '创作模型 + 品牌资料库',
    promptQuery: '营销活动策划',
  },
  {
    slug: 'sales-proposal',
    name: '制作销售提案',
    category: '商业与增长',
    summary: '把客户需求、解决方案、证据和下一步组成提案。',
    steps: ['整理客户目标、痛点和约束', '对齐方案、价值和实施路径', '补证据、风险和行动请求'],
    stack: '长文本模型 + 客户资料',
    promptQuery: '销售提案',
  },
  {
    slug: 'customer-message',
    name: '回复客户',
    category: '商业与增长',
    summary: '根据上下文处理咨询、异议、投诉和后续跟进。',
    steps: ['提供完整对话和客户状态', '先确认问题与情绪', '给出解决方案、边界和下一步'],
    stack: '快速对话模型 + 客服知识库',
    promptQuery: '客诉回复',
  },
  {
    slug: 'analyze-data',
    name: '分析业务数据',
    category: '商业与增长',
    summary: '定义指标、检查数据、解释变化并形成行动建议。',
    steps: ['说明业务问题和指标口径', '清洗数据并验证异常', '区分相关与因果并给出实验'],
    stack: '强推理模型 + Python／SQL',
    promptQuery: '数据分析方案',
  },
  {
    slug: 'financial-budget',
    name: '做财务预算',
    category: '商业与增长',
    summary: '建立收入、成本、现金和不同经营情景的预算。',
    steps: ['提供历史数据和经营驱动', '建立基准、乐观和压力情景', '检查现金低点并由财务复核'],
    stack: '分析模型 + 电子表格',
    promptQuery: '财务情景预测',
  },
  {
    slug: 'write-prd',
    name: '写 PRD',
    category: '设计与产品',
    summary: '把用户问题转成范围清楚、可以验收的产品需求。',
    steps: ['提供用户证据和业务目标', '定义场景、边界和成功指标', '补异常流程与验收标准'],
    stack: '长文本模型 + 用户研究资料',
    promptQuery: 'PRD 需求文档',
  },
  {
    slug: 'design-prototype',
    name: '做页面与原型',
    category: '设计与产品',
    summary: '从用户流程到页面结构、状态和交互说明。',
    steps: ['明确核心任务和设备', '画用户流程与低保真结构', '补状态、文案并进行可用性测试'],
    stack: '多模态模型 + 原型工具',
    promptQuery: '设计评审',
  },
  {
    slug: 'user-research',
    name: '做用户研究',
    category: '设计与产品',
    summary: '设计访谈、整理证据并形成可验证的产品洞察。',
    steps: ['定义研究问题和招募标准', '设计非诱导问题并执行访谈', '编码证据并标注置信度'],
    stack: '长文本模型 + 访谈资料',
    promptQuery: '用户访谈分析',
  },
  {
    slug: 'brand-positioning',
    name: '做品牌定位',
    category: '设计与产品',
    summary: '明确目标人群、竞争参照、价值主张和可信证据。',
    steps: ['提供客户、品类和竞争资料', '生成并比较定位假设', '用真实客户测试理解和差异'],
    stack: '强推理模型 + 市场研究',
    promptQuery: '品牌定位',
  },
  {
    slug: 'ecommerce-page',
    name: '做电商详情页',
    category: '设计与产品',
    summary: '围绕购买决策设计卖点、证据、图片和页面顺序。',
    steps: ['整理产品事实和用户疑虑', '设计信息层级与内容模块', '检查平台规则并测试转化'],
    stack: '多模态模型 + 商品资料',
    promptQuery: '电商详情页优化',
  },
  {
    slug: 'create-visual',
    name: '生成图片与视觉',
    category: '设计与产品',
    summary: '把用途、构图、风格和限制写成可控的视觉任务。',
    steps: ['定义用途、尺寸和品牌规范', '制作参考方向与生成提示', '检查文字、细节、版权和一致性'],
    stack: '图像生成模型 + 设计工具',
    promptQuery: '体验设计',
  },
];
